Also make sure the log export always runs.

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -31,9 +31,12 @@ jobs:
           export RUST_BACKTRACE=full
           export KEEP_KIND=true
           cargo test -- --nocapture
-      - run: |
+      - name: Export Kind logs
+        if: success() || failure() # always run even if the previous step fails
+        run: |
           kind export logs --name odcs-test kind_logs
-      - uses: actions/upload-artifact@v4.6.2
+      - name: Upload Kind logs
+        uses: actions/upload-artifact@v4.6.2
         if: success() || failure() # always run even if the previous step fails
         with:
           name: kind-logs
